name: microservice-catalog
services:
  database:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=api
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d api"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: nest-rms
  #   environment:
  #     - DATABASE_URL=postgresql://postgres:postgres@db:5432/rms?schema=public
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - db

networks:
  microservice-catalog-network:
    driver: bridge

volumes:
  postgres_data: