apiVersion: v1
kind: Secret
metadata:
  name: rms-catalog-secrets
type: Opaque
data:
  PORT: 3002
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQHBvc3RncmVzLXNlcnZpY2U6NTQzMi9ybXM/c2NoZW1hPXB1YmxpYw==
  REDIS_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQHBvc3RncmVzLXNlcnZpY2U6NTQzMi9ybXM/c2NoZW1hPXB1YmxpYw==