apiVersion: v1
kind: Secret
metadata:
  name: rms-catalog-secrets
type: Opaque
data:
  PORT: MzAwMg==
  DATABASE_URL: cG9zdGdyZXNxbDovL3Jtc3Bvc3RncmVzOnJtc3Bvc3RncmVzQGNhdGFsb2ctZGIuY2swb3NvYmJ0enZzLnVzLWVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbTo1NDMyL3Jtcz9zY2hlbWE9cHVibGlj
  REDIS_URL: cmVkaXM6Ly9ybXMtcmVkaXMtY2x1c3Rlci56aHN4emguMDAwMS51c2UxLmNhY2hlLmFtYXpvbmF3cy5jb206NjM3OQ==