apiVersion: v1
kind: Service
metadata:
  name: rms-customer-service
  namespace: rms-customer
spec:
  selector:
    app: rms-catalog
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3002